# Inciso 6.3- 6.6

### Librerías importadas.

In [2]:
pip install xgboost

Collecting xgboost
  Downloading xgboost-3.4.1-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in c:\users\aripi\anaconda3\envs\datamining\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\users\aripi\anaconda3\envs\datamining\lib\site-packages (from xgboost) (1.17.0)
Downloading xgboost-3.4.1-py3-none-win_amd64.whl (48.9 MB)
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.5/48.9 MB 429.7 kB/s eta 0:01:53
    --------------------------------------- 0.8/48.9 MB 588.4 kB/s eta 0:01:22
    --------------------------------------- 1.0/48.9 MB 689.2 kB/s eta 0:01:10
   - -------------------------------------- 1.3/48.9 MB 762.6 kB/s eta 0:01:03
   - -------------------------------------- 1.3/48.9 MB 762.6 kB/s eta 0:01:03
   - -------------------------------------- 1.6/48.9 MB 791.0 kB/s eta 0:01:00
   - -------------------------------------- 1.8/48.9 MB 798.8 kB/s eta 0:00:59
   - -------------------------------------- 1.8/48.9 MB 798.8 kB/s eta 0:00:59
   - -------------------------------------- 1.8/48.9 MB 798.8 kB/s eta 0:00:59
   - -------------------------------------- 1.8/48.9 MB 798.8 kB/s eta 0:00:59
   - -------------------------------------- 2.1/48.9 MB 652.3 kB/s eta 0:01:12
   - -------------------------------------- 2.1/48.9 MB 652.3 kB/s eta 0:01:12
   - -------------------------------------- 2.4/48.9 MB 677.8 kB/s eta 0:01:09
   -- ------------------------------------- 2.6/48.9 MB 705.5 kB/s eta 0:01:06
   -- ------------------------------------- 2.9/48.9 MB 735.7 kB/s eta 0:01:03
   -- ------------------------------------- 3.1/48.9 MB 762.4 kB/s eta 0:01:01
   -- ------------------------------------- 3.4/48.9 MB 786.4 kB/s eta 0:00:58
   -- ------------------------------------- 3.7/48.9 MB 810.8 kB/s eta 0:00:56
   --- ------------------------------------ 3.9/48.9 MB 829.9 kB/s eta 0:00:55
   --- ------------------------------------ 4.2/48.9 MB 841.6 kB/s eta 0:00:54
   --- ------------------------------------ 4.2/48.9 MB 841.6 kB/s eta 0:00:54
   --- ------------------------------------ 4.2/48.9 MB 841.6 kB/s eta 0:00:54
   --- ------------------------------------ 4.2/48.9 MB 841.6 kB/s eta 0:00:54
   --- ------------------------------------ 4.5/48.9 MB 778.0 kB/s eta 0:00:58
   --- ------------------------------------ 4.7/48.9 MB 781.4 kB/s eta 0:00:57
   ---- ----------------------------------- 5.0/48.9 MB 794.6 kB/s eta 0:00:56
   ---- ----------------------------------- 5.2/48.9 MB 809.0 kB/s eta 0:00:55
   ---- ----------------------------------- 5.5/48.9 MB 822.4 kB/s eta 0:00:53
   ---- ----------------------------------- 5.8/48.9 MB 836.9 kB/s eta 0:00:52
   ---- ----------------------------------- 5.8/48.9 MB 836.9 kB/s eta 0:00:52
   ---- ----------------------------------- 6.0/48.9 MB 840.7 kB/s eta 0:00:52
   ----- ---------------------------------- 6.3/48.9 MB 842.4 kB/s eta 0:00:51
   ----- ---------------------------------- 6.6/48.9 MB 853.1 kB/s eta 0:00:50
   ----- ---------------------------------- 6.8/48.9 MB 864.8 kB/s eta 0:00:49
   ----- ---------------------------------- 7.1/48.9 MB 874.1 kB/s eta 0:00:48
   ----- ---------------------------------- 7.1/48.9 MB 874.1 kB/s eta 0:00:48
   ----- ---------------------------------- 7.1/48.9 MB 874.1 kB/s eta 0:00:48
   ----- ---------------------------------- 7.3/48.9 MB 840.4 kB/s eta 0:00:50
   ------ --------------------------------- 7.6/48.9 MB 849.4 kB/s eta 0:00:49
   ------ --------------------------------- 7.9/48.9 MB 858.0 kB/s eta 0:00:48
   ------ --------------------------------- 8.1/48.9 MB 867.7 kB/s eta 0:00:48
   ------ --------------------------------- 8.4/48.9 MB 875.5 kB/s eta 0:00:47
   ------- -------------------------------- 8.7/48.9 MB 883.0 kB/s eta 0:00:46
   ------- -------------------------------- 8.9/48.9 MB 888.6 kB/s eta 0:00:46
   ------- -------------------------------- 8.9/48.9 MB 888.6 kB/s eta 0:00:46
   ------- -------------------------------- 9.2/48.9 MB 895.5 kB/s eta 0:00:45
   ------- -------------------------------- 9.4/48.9 MB 897.8 kB/s eta 0:00:45
   ------- -------------------------------- 9.7/48.9 MB 902.8 kB/s eta 0:00:44
   -------- ------------------------------- 10.0/48.9 MB 907.5 kB/s eta 0:00:43
   -------- ------------------------------- 10.0/48.9 MB 907.5 kB/s eta 0:00:43
   -------- ------------------------------- 10.2/48.9 MB 905.6 kB/s eta 0:00:43
   -------- ------------------------------- 10.2/48.9 MB 905.6 kB/s eta 0:00:43
   -------- ------------------------------- 10.2/48.9 MB 905.6 kB/s eta 0:00:43
   -------- ------------------------------- 10.5/48.9 MB 879.5 kB/s eta 0:00:44
   -------- ------------------------------- 10.5/48.9 MB 879.5 kB/s eta 0:00:44
   -------- ------------------------------- 10.7/48.9 MB 858.2 kB/s eta 0:00:45
   -------- ------------------------------- 10.7/48.9 MB 858.2 kB/s eta 0:00:45
   -------- ------------------------------- 10.7/48.9 MB 858.2 kB/s eta 0:00:45
   -------- ------------------------------- 11.0/48.9 MB 839.9 kB/s eta 0:00:46
   -------- ------------------------------- 11.0/48.9 MB 839.9 kB/s eta 0:00:46
   --------- ------------------------------ 11.3/48.9 MB 828.9 kB/s eta 0:00:46
   --------- ------------------------------ 11.3/48.9 MB 828.9 kB/s eta 0:00:46
   --------- ------------------------------ 11.5/48.9 MB 835.0 kB/s eta 0:00:45
   --------- ------------------------------ 11.8/48.9 MB 840.8 kB/s eta 0:00:45
   --------- ------------------------------ 12.1/48.9 MB 845.4 kB/s eta 0:00:44
   ---------- ----------------------------- 12.3/48.9 MB 851.8 kB/s eta 0:00:43
   ---------- ----------------------------- 12.3/48.9 MB 851.8 kB/s eta 0:00:43
   ---------- ----------------------------- 12.6/48.9 MB 842.4 kB/s eta 0:00:44
   ---------- ----------------------------- 12.6/48.9 MB 842.4 kB/s eta 0:00:44
   ---------- ----------------------------- 12.6/48.9 MB 842.4 kB/s eta 0:00:44
   ---------- ----------------------------- 12.8/48.9 MB 828.5 kB/s eta 0:00:44
   ---------- ----------------------------- 12.8/48.9 MB 828.5 kB/s eta 0:00:44
   ---------- ----------------------------- 13.1/48.9 MB 818.8 kB/s eta 0:00:44
   ---------- ----------------------------- 13.1/48.9 MB 818.8 kB/s eta 0:00:44
   ---------- ----------------------------- 13.4/48.9 MB 815.2 kB/s eta 0:00:44
   ----------- ---------------------------- 13.6/48.9 MB 821.1 kB/s eta 0:00:44
   ----------- ---------------------------- 13.9/48.9 MB 826.1 kB/s eta 0:00:43
   ----------- ---------------------------- 14.2/48.9 MB 831.0 kB/s eta 0:00:42
   ----------- ---------------------------- 14.2/48.9 MB 831.0 kB/s eta 0:00:42
   ----------- ---------------------------- 14.2/48.9 MB 831.0 kB/s eta 0:00:42
   ----------- ---------------------------- 14.4/48.9 MB 816.9 kB/s eta 0:00:43
   ----------- ---------------------------- 14.4/48.9 MB 816.9 kB/s eta 0:00:43
   ----------- ---------------------------- 14.4/48.9 MB 816.9 kB/s eta 0:00:43
   ----------- ---------------------------- 14.7/48.9 MB 802.4 kB/s eta 0:00:43
   ----------- ---------------------------- 14.7/48.9 MB 802.4 kB/s eta 0:00:43
   ------------ --------------------------- 14.9/48.9 MB 795.5 kB/s eta 0:00:43
   ------------ --------------------------- 14.9/48.9 MB 795.5 kB/s eta 0:00:43
   ------------ --------------------------- 15.2/48.9 MB 797.6 kB/s eta 0:00:43
   ------------ --------------------------- 15.5/48.9 MB 802.8 kB/s eta 0:00:42
   ------------ --------------------------- 15.7/48.9 MB 807.4 kB/s eta 0:00:42
   ------------- -------------------------- 16.0/48.9 MB 807.2 kB/s eta 0:00:41
   ------------- -------------------------- 16.0/48.9 MB 807.2 kB/s eta 0:00:41
   ------------- -------------------------- 16.0/48.9 MB 807.2 kB/s eta 0:00:41
   ------------- -------------------------- 16.3/48.9 MB 801.4 kB/s eta 0:00:41
   ------------- -------------------------- 16.3/48.9 MB 801.4 kB/s eta 0:00:41
   ------------- -------------------------- 16.5/48.9 MB 794.6 kB/s eta 0:00:41
   ------------- -------------------------- 16.5/48.9 MB 794.6 kB/s eta 0:00:41
   ------------- -------------------------- 16.8/48.9 MB 792.9 kB/s eta 0:00:41
   ------------- -------------------------- 17.0/48.9 MB 797.7 kB/s eta 0:00:40
   -------------- ------------------------- 17.3/48.9 MB 801.2 kB/s eta 0:00:40
   -------------- ------------------------- 17.6/48.9 MB 805.3 kB/s eta 0:00:39
   -------------- ------------------------- 17.8/48.9 MB 809.8 kB/s eta 0:00:39
   -------------- ------------------------- 18.1/48.9 MB 813.7 kB/s eta 0:00:38
   -------------- ------------------------- 18.4/48.9 MB 818.1 kB/s eta 0:00:38
   --------------- ------------------------ 18.6/48.9 MB 821.8 kB/s eta 0:00:37
   --------------- ------------------------ 18.9/48.9 MB 825.5 kB/s eta 0:00:37
   --------------- ------------------------ 19.1/48.9 MB 829.1 kB/s eta 0:00:36
   --------------- ------------------------ 19.4/48.9 MB 832.6 kB/s eta 0:00:36
   ---------------- ----------------------- 19.7/48.9 MB 836.0 kB/s eta 0:00:36
   ---------------- ----------------------- 19.9/48.9 MB 839.4 kB/s eta 0:00:35
   ---------------- ----------------------- 19.9/48.9 MB 839.4 kB/s eta 0:00:35
   ---------------- ----------------------- 20.2/48.9 MB 839.4 kB/s eta 0:00:35
   ---------------- ----------------------- 20.2/48.9 MB 839.4 kB/s eta 0:00:35
   ---------------- ----------------------- 20.4/48.9 MB 832.9 kB/s eta 0:00:35
   ---------------- ----------------------- 20.4/48.9 MB 832.9 kB/s eta 0:00:35
   ---------------- ----------------------- 20.4/48.9 MB 832.9 kB/s eta 0:00:35
   ---------------- ----------------------- 20.7/48.9 MB 827.7 kB/s eta 0:00:35
   ---------------- ----------------------- 20.7/48.9 MB 827.7 kB/s eta 0:00:35
   ----------------- ---------------------- 21.0/48.9 MB 824.3 kB/s eta 0:00:34
   ----------------- ---------------------- 21.2/48.9 MB 827.5 kB/s eta 0:00:34
   ----------------- ---------------------- 21.5/48.9 MB 830.6 kB/s eta 0:00:34
   ----------------- ---------------------- 21.8/48.9 MB 833.8 kB/s eta 0:00:33
   ----------------- ---------------------- 22.0/48.9 MB 837.3 kB/s eta 0:00:33
   ------------------ --------------------- 22.3/48.9 MB 839.9 kB/s eta 0:00:32
   ------------------ --------------------- 22.5/48.9 MB 843.3 kB/s eta 0:00:32
   ------------------ --------------------- 22.8/48.9 MB 846.2 kB/s eta 0:00:31
   ------------------ --------------------- 23.1/48.9 MB 849.1 kB/s eta 0:00:31
   ------------------- -------------------- 23.3/48.9 MB 850.9 kB/s eta 0:00:31
   ------------------- -------------------- 23.3/48.9 MB 850.9 kB/s eta 0:00:31
   ------------------- -------------------- 23.6/48.9 MB 851.8 kB/s eta 0:00:30
   ------------------- -------------------- 23.9/48.9 MB 851.6 kB/s eta 0:00:30
   ------------------- -------------------- 23.9/48.9 MB 851.6 kB/s eta 0:00:30
   ------------------- -------------------- 24.1/48.9 MB 846.3 kB/s eta 0:00:30
   ------------------- -------------------- 24.1/48.9 MB 846.3 kB/s eta 0:00:30
   ------------------- -------------------- 24.1/48.9 MB 846.3 kB/s eta 0:00:30
   ------------------- -------------------- 24.4/48.9 MB 840.2 kB/s eta 0:00:30
   ------------------- -------------------- 24.4/48.9 MB 840.2 kB/s eta 0:00:30
   -------------------- ------------------- 24.6/48.9 MB 839.3 kB/s eta 0:00:29
   -------------------- ------------------- 24.9/48.9 MB 842.4 kB/s eta 0:00:29
   -------------------- ------------------- 25.2/48.9 MB 845.1 kB/s eta 0:00:29
   -------------------- ------------------- 25.4/48.9 MB 847.7 kB/s eta 0:00:28
   -------------------- ------------------- 25.7/48.9 MB 850.7 kB/s eta 0:00:28
   --------------------- ------------------ 26.0/48.9 MB 862.0 kB/s eta 0:00:27
   --------------------- ------------------ 26.2/48.9 MB 864.5 kB/s eta 0:00:27
   --------------------- ------------------ 26.5/48.9 MB 866.9 kB/s eta 0:00:26
   --------------------- ------------------ 26.7/48.9 MB 868.7 kB/s eta 0:00:26
   ---------------------- ----------------- 27.0/48.9 MB 870.1 kB/s eta 0:00:26
   ---------------------- ----------------- 27.3/48.9 MB 870.5 kB/s eta 0:00:25
   ---------------------- ----------------- 27.5/48.9 MB 872.3 kB/s eta 0:00:25
   ---------------------- ----------------- 27.5/48.9 MB 872.3 kB/s eta 0:00:25
   ---------------------- ----------------- 27.8/48.9 MB 871.9 kB/s eta 0:00:25
   ---------------------- ----------------- 27.8/48.9 MB 871.9 kB/s eta 0:00:25
   ---------------------- ----------------- 27.8/48.9 MB 871.9 kB/s eta 0:00:25
   ---------------------- ----------------- 28.0/48.9 MB 876.0 kB/s eta 0:00:24
   ---------------------- ----------------- 28.0/48.9 MB 876.0 kB/s eta 0:00:24
   ----------------------- ---------------- 28.3/48.9 MB 870.5 kB/s eta 0:00:24
   ----------------------- ---------------- 28.6/48.9 MB 869.6 kB/s eta 0:00:24
   ----------------------- ---------------- 28.6/48.9 MB 869.6 kB/s eta 0:00:24
   ----------------------- ---------------- 28.8/48.9 MB 869.6 kB/s eta 0:00:24
   ----------------------- ---------------- 29.1/48.9 MB 868.7 kB/s eta 0:00:23
   ----------------------- ---------------- 29.4/48.9 MB 867.3 kB/s eta 0:00:23
   ------------------------ --------------- 29.6/48.9 MB 866.4 kB/s eta 0:00:23
   ------------------------ --------------- 29.9/48.9 MB 866.9 kB/s eta 0:00:22
   ------------------------ --------------- 30.1/48.9 MB 866.0 kB/s eta 0:00:22
   ------------------------ --------------- 30.1/48.9 MB 866.0 kB/s eta 0:00:22
   ------------------------ --------------- 30.4/48.9 MB 876.5 kB/s eta 0:00:22
   ------------------------ --------------- 30.4/48.9 MB 876.5 kB/s eta 0:00:22
   ------------------------ --------------- 30.4/48.9 MB 876.5 kB/s eta 0:00:22
   ------------------------- -------------- 30.7/48.9 MB 869.6 kB/s eta 0:00:22
   ------------------------- -------------- 30.7/48.9 MB 869.6 kB/s eta 0:00:22
   ------------------------- -------------- 30.7/48.9 MB 869.6 kB/s eta 0:00:22
   ------------------------- -------------- 30.9/48.9 MB 856.3 kB/s eta 0:00:22
   ------------------------- -------------- 30.9/48.9 MB 856.3 kB/s eta 0:00:22
   ------------------------- -------------- 31.2/48.9 MB 845.0 kB/s eta 0:00:22
   ------------------------- -------------- 31.5/48.9 MB 845.0 kB/s eta 0:00:21
   ------------------------- -------------- 31.5/48.9 MB 845.0 kB/s eta 0:00:21
   ------------------------- -------------- 31.7/48.9 MB 842.8 kB/s eta 0:00:21
   -------------------------- ------------- 32.0/48.9 MB 842.8 kB/s eta 0:00:21
   -------------------------- ------------- 32.2/48.9 MB 842.8 kB/s eta 0:00:20
   -------------------------- ------------- 32.5/48.9 MB 851.7 kB/s eta 0:00:20
   -------------------------- ------------- 32.5/48.9 MB 851.7 kB/s eta 0:00:20
   -------------------------- ------------- 32.5/48.9 MB 851.7 kB/s eta 0:00:20
   -------------------------- ------------- 32.8/48.9 MB 840.2 kB/s eta 0:00:20
   -------------------------- ------------- 32.8/48.9 MB 840.2 kB/s eta 0:00:20
   -------------------------- ------------- 32.8/48.9 MB 840.2 kB/s eta 0:00:20
   -------------------------- ------------- 33.0/48.9 MB 823.1 kB/s eta 0:00:20
   -------------------------- ------------- 33.0/48.9 MB 823.1 kB/s eta 0:00:20
   -------------------------- ------------- 33.0/48.9 MB 823.1 kB/s eta 0:00:20
   --------------------------- ------------ 33.3/48.9 MB 809.0 kB/s eta 0:00:20
   --------------------------- ------------ 33.6/48.9 MB 809.8 kB/s eta 0:00:20
   --------------------------- ------------ 33.8/48.9 MB 813.1 kB/s eta 0:00:19
   --------------------------- ------------ 34.1/48.9 MB 813.9 kB/s eta 0:00:19
   ---------------------------- ----------- 34.3/48.9 MB 814.4 kB/s eta 0:00:18
   ---------------------------- ----------- 34.6/48.9 MB 817.3 kB/s eta 0:00:18
   ---------------------------- ----------- 34.9/48.9 MB 827.3 kB/s eta 0:00:18
   ---------------------------- ----------- 35.1/48.9 MB 830.0 kB/s eta 0:00:17
   ---------------------------- ----------- 35.4/48.9 MB 832.7 kB/s eta 0:00:17
   ----------------------------- ---------- 35.7/48.9 MB 843.3 kB/s eta 0:00:16
   ----------------------------- ---------- 35.7/48.9 MB 843.3 kB/s eta 0:00:16
   ----------------------------- ---------- 35.9/48.9 MB 844.6 kB/s eta 0:00:16
   ----------------------------- ---------- 36.2/48.9 MB 852.2 kB/s eta 0:00:15
   ----------------------------- ---------- 36.2/48.9 MB 852.2 kB/s eta 0:00:15
   ----------------------------- ---------- 36.4/48.9 MB 852.0 kB/s eta 0:00:15
   ----------------------------- ---------- 36.4/48.9 MB 852.0 kB/s eta 0:00:15
   ----------------------------- ---------- 36.7/48.9 MB 854.7 kB/s eta 0:00:15
   ----------------------------- ---------- 36.7/48.9 MB 854.7 kB/s eta 0:00:15
   ------------------------------ --------- 37.0/48.9 MB 849.4 kB/s eta 0:00:15
   ------------------------------ --------- 37.2/48.9 MB 841.9 kB/s eta 0:00:14
   ------------------------------ --------- 37.2/48.9 MB 841.9 kB/s eta 0:00:14
   ------------------------------ --------- 37.5/48.9 MB 841.5 kB/s eta 0:00:14
   ------------------------------ --------- 37.7/48.9 MB 848.6 kB/s eta 0:00:14
   ------------------------------- -------- 38.0/48.9 MB 851.6 kB/s eta 0:00:13
   ------------------------------- -------- 38.3/48.9 MB 861.5 kB/s eta 0:00:13
   ------------------------------- -------- 38.5/48.9 MB 864.0 kB/s eta 0:00:13
   ------------------------------- -------- 38.8/48.9 MB 866.9 kB/s eta 0:00:12
   ------------------------------- -------- 39.1/48.9 MB 875.1 kB/s eta 0:00:12
   -------------------------------- ------- 39.3/48.9 MB 877.5 kB/s eta 0:00:11
   -------------------------------- ------- 39.6/48.9 MB 882.5 kB/s eta 0:00:11
   -------------------------------- ------- 39.8/48.9 MB 885.3 kB/s eta 0:00:11
   -------------------------------- ------- 39.8/48.9 MB 885.3 kB/s eta 0:00:11
   -------------------------------- ------- 40.1/48.9 MB 877.5 kB/s eta 0:00:11
   -------------------------------- ------- 40.1/48.9 MB 877.5 kB/s eta 0:00:11
   -------------------------------- ------- 40.4/48.9 MB 877.9 kB/s eta 0:00:10
   -------------------------------- ------- 40.4/48.9 MB 877.9 kB/s eta 0:00:10
   --------------------------------- ------ 40.6/48.9 MB 877.5 kB/s eta 0:00:10
   --------------------------------- ------ 40.9/48.9 MB 888.6 kB/s eta 0:00:10
   --------------------------------- ------ 41.2/48.9 MB 890.9 kB/s eta 0:00:09
   --------------------------------- ------ 41.4/48.9 MB 893.6 kB/s eta 0:00:09
   ---------------------------------- ----- 41.7/48.9 MB 901.6 kB/s eta 0:00:09
   ---------------------------------- ----- 41.9/48.9 MB 904.2 kB/s eta 0:00:08
   ---------------------------------- ----- 42.2/48.9 MB 905.7 kB/s eta 0:00:08
   ---------------------------------- ----- 42.5/48.9 MB 905.2 kB/s eta 0:00:08
   ---------------------------------- ----- 42.7/48.9 MB 905.7 kB/s eta 0:00:07
   ----------------------------------- ---- 43.0/48.9 MB 909.0 kB/s eta 0:00:07
   ----------------------------------- ---- 43.3/48.9 MB 909.2 kB/s eta 0:00:07
   ----------------------------------- ---- 43.3/48.9 MB 909.2 kB/s eta 0:00:07

In [11]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
import matplotlib.pyplot as plt
import math
from sklearn.metrics import f1_score, classification_report, roc_auc_score, ConfusionMatrixDisplay
from sklearn.model_selection import GroupShuffleSplit

### Importación de datos.

In [2]:
df = pd.read_csv('datos_predictores_bloques.csv')
df.head(2)

,lago,fecha,bloque_fila,bloque_columna,x,y,b03,b04,b05,b08,ndci,ndvi,ndwi,proporcion_agua,proporcion_tierra,proporcion_otro,chl_a_estimada,pixeles_validos,alta_cianobacteria,id_bloque
0,amatitlan,2025-01-28,1594,754,754500.0,1594500.0,0.132696,0.138698,0.144296,0.184101,0.032449,0.145970,-0.164748,0.009569,0.251196,0.739234,4.664739,418,0,amatitlan_1594_754
1,amatitlan,2025-01-28,1594,755,755500.0,1594500.0,0.088559,0.080894,0.100493,0.206473,0.147543,0.441826,-0.395174,0.003158,0.763158,0.233684,8.154140,950,0,amatitlan_1594_755

### Valores faltantes.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7194 entries, 0 to 7193
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   lago                7194 non-null   object
 1   fecha               7194 non-null   object
 2   bloque_fila         7194 non-null   int64
 3   bloque_columna      7194 non-null   int64
 4   x                   7194 non-null   float64
 5   y                   7194 non-null   float64
 6   b03                 7194 non-null   float64
 7   b04                 7194 non-null   float64
 8   b05                 7194 non-null   float64
 9   b08                 7194 non-null   float64
 10  ndci                7194 non-null   float64
 11  ndvi                7194 non-null   float64
 12  ndwi                7194 non-null   float64
 13  proporcion_agua     7194 non-null   float64
 14  proporcion_tierra   7194 non-null   float64
 15  proporcion_otro     7194 non-null   float64
 16  chl_a_estimada      7194 non-null   float64
 17  pixeles_validos     7194 non-null   int64
 18  alta_cianobacteria  7194 non-null   int64
 19  id_bloque           7194 non-null   object
dtypes: float64(13), int64(4), object(3)
memory usage: 1.1+ MB

No hay valores faltantes.

### Muestra de datos

In [4]:
proporcion = 0.01
df, _ = train_test_split(df, train_size=proporcion, stratify=df["alta_cianobacteria"], random_state=0)
df = df.reset_index(drop=True)

In [5]:
df.shape

(71, 20)

### Etiquetas y variable objetivo.

In [37]:
columnas_excluir = [
    "lago",
    "fecha",
    "alta_cianobacteria",
    "ndci",
    "chl_a_estimada",
    "b04",
    "b05",
    "id_bloque",
    "celda_fila",
    "celda_columna"
]

X = df.drop(
    columns=columnas_excluir,
    errors="ignore"
)

y = df["alta_cianobacteria"].astype(int)

### Conjunto de entrenamiento y prueba (para la validación aleatoria)

In [38]:
X_train_aleatorio, X_test_aleatorio, y_train_aleatorio, y_test_aleatorio = train_test_split(X, y, test_size=0.30, random_state=42, stratify=y)

### Conjunto de entrenamiento (para validación espacial)

In [39]:
groups = df["id_bloque"]
gss = GroupShuffleSplit(
    n_splits=1,
    test_size=0.30,
    random_state=42
)

idx_train_esp, idx_test_esp = next(
    gss.split(
        X,
        y,
        groups=groups
    )
)

X_train_esp = X.iloc[idx_train_esp].copy()
X_test_esp = X.iloc[idx_test_esp].copy()

y_train_esp = y.iloc[idx_train_esp].copy()
y_test_esp = y.iloc[idx_test_esp].copy()

groups_train_esp = groups.iloc[idx_train_esp].copy()
groups_test_esp = groups.iloc[idx_test_esp].copy()

In [40]:
#Comprobación de que se ha separado correctamente
assert set(groups_train_esp).isdisjoint(
    set(groups_test_esp)
)

print(
    "Bloques train:",
    groups_train_esp.nunique()
)

print(
    "Bloques test:",
    groups_test_esp.nunique()
)

print(
    "Bloques compartidos:",
    len(
        set(groups_train_esp)
        &
        set(groups_test_esp)
    )
)

Bloques train: 46
Bloques test: 20
Bloques compartidos: 0

## Regresión logística.

### Preprocesamiento a utilizar.

In [41]:
pipeline_rl = Pipeline(steps=[("minmax_scaler", MinMaxScaler()),
                                   ("modelo", LogisticRegression(max_iter=1000, random_state=0))])

### Rejilla de hiperparámetros.

In [42]:
#rejilla_rl = [
#    {
#        "modelo__solver": ["liblinear"],
#        "modelo__penalty": ["l1", "l2"],
#        "modelo__C": [0.01, 0.1, 1, 10]
#    },
#    {
#        "modelo__solver": ["lbfgs"],
#        "modelo__penalty": ["l2"],
#        "modelo__C": [0.01, 0.1, 1, 10]
#    }
#]

rejilla_rl = [{'modelo__C': [10], 'modelo__penalty': ['l2'], 'modelo__solver': ['liblinear']}]

### GridSearch -aleatorio-.

In [43]:
grid_search_rl = GridSearchCV(
    estimator=pipeline_rl,
    param_grid=rejilla_rl,
    scoring="f1",
    cv=5,
    n_jobs=-1,
    verbose=1,
    return_train_score=True
)

### GridSearch -espacial-

In [44]:
from sklearn.model_selection import StratifiedGroupKFold

cv_espacial = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)
#GRIDSEARCH REGRESIÓN LOGÍSTICA
grid_rl_esp = GridSearchCV(
    estimator=pipeline_rl,
    param_grid=rejilla_rl,
    scoring="f1",
    cv=cv_espacial,
    n_jobs=-1,
    return_train_score=True
)

### Entrenamiento del modelo.

In [45]:
grid_search_rl.fit(X_train_aleatorio, y_train_aleatorio)

Fitting 5 folds for each of 1 candidates, totalling 5 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('minmax_scaler', MinMaxScaler()),
                                       ('modelo',
                                        LogisticRegression(max_iter=1000,
                                                           random_state=0))]),
             n_jobs=-1,
             param_grid=[{'modelo__C': [10], 'modelo__penalty': ['l2'],
                          'modelo__solver': ['liblinear']}],
             return_train_score=True, scoring='f1', verbose=1)

In [46]:
grid_rl_esp.fit(X_train_esp,y_train_esp,groups=groups_train_esp) #ESPACIAL

GridSearchCV(cv=StratifiedGroupKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('minmax_scaler', MinMaxScaler()),
                                       ('modelo',
                                        LogisticRegression(max_iter=1000,
                                                           random_state=0))]),
             n_jobs=-1,
             param_grid=[{'modelo__C': [10], 'modelo__penalty': ['l2'],
                          'modelo__solver': ['liblinear']}],
             return_train_score=True, scoring='f1')

### Mejor modelo e hiperparámetros.

In [47]:
print("Mejores hiperparámetros:", grid_search_rl.best_params_)
print("Mejor accuracy promedio en validación:", grid_search_rl.best_score_)

mejor_lr = grid_search_rl.best_estimator_

Mejores hiperparámetros: {'modelo__C': 10, 'modelo__penalty': 'l2', 'modelo__solver': 'liblinear'}
Mejor accuracy promedio en validación: 0.811010101010101

## Random Forest.

### Preprocesamiento a utilizar.

In [48]:
pipeline_rf = Pipeline(steps=[("preprocesamiento", MinMaxScaler(feature_range=(0, 1))),
                              ("modelo", RandomForestClassifier(random_state=42))])

### Rejilla de hiperparámetros.

In [49]:
#rejilla_rf = {
#    "modelo__n_estimators": [50, 100, 200],
#    "modelo__max_depth": [3, 5, 7],
#    "modelo__min_samples_split": [2, 5, 8],
#    "modelo__min_samples_leaf": [1, 2, 4],
#    "modelo__max_features": ["sqrt", "log2"]
#}
rejilla_rf = {
    "modelo__n_estimators": [200],
    "modelo__max_depth": [7],
    "modelo__min_samples_split": [5],
    "modelo__min_samples_leaf": [1],
    "modelo__max_features": ["sqrt"]
}

### GridSearch -Aleatorio-

In [50]:
grid_search_rf = GridSearchCV(
    estimator=pipeline_rf,
    param_grid=rejilla_rf,
    scoring="f1",
    cv=5,
    n_jobs=-1,
    verbose=1,
    return_train_score=True
)

### GridSearch -Espacial-

In [51]:
grid_rf_esp = GridSearchCV(
    estimator=pipeline_rf,
    param_grid=rejilla_rf,
    scoring="f1",
    cv=cv_espacial,
    n_jobs=-1,
    return_train_score=True
)

### Entrenamiento del modelo.

In [52]:
grid_search_rf.fit(X_train_aleatorio, y_train_aleatorio)

Fitting 5 folds for each of 1 candidates, totalling 5 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocesamiento', MinMaxScaler()),
                                       ('modelo',
                                        RandomForestClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'modelo__max_depth': [7],
                         'modelo__max_features': ['sqrt'],
                         'modelo__min_samples_leaf': [1],
                         'modelo__min_samples_split': [5],
                         'modelo__n_estimators': [200]},
             return_train_score=True, scoring='f1', verbose=1)

In [53]:
grid_rf_esp.fit(X_train_esp,y_train_esp,groups=groups_train_esp)

GridSearchCV(cv=StratifiedGroupKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('preprocesamiento', MinMaxScaler()),
                                       ('modelo',
                                        RandomForestClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'modelo__max_depth': [7],
                         'modelo__max_features': ['sqrt'],
                         'modelo__min_samples_leaf': [1],
                         'modelo__min_samples_split': [5],
                         'modelo__n_estimators': [200]},
             return_train_score=True, scoring='f1')

### Mejor modelo e hiperparámetros.

In [54]:
print("Mejores hiperparámetros:", grid_search_rf.best_params_)
print("Mejor accuracy en validación:", grid_search_rf.best_score_)
mejor_rf = grid_search_rf.best_estimator_

Mejores hiperparámetros: {'modelo__max_depth': 7, 'modelo__max_features': 'sqrt', 'modelo__min_samples_leaf': 1, 'modelo__min_samples_split': 5, 'modelo__n_estimators': 200}
Mejor accuracy en validación: 0.8533333333333333

## XGBoost

### Preprocesamiento a utilizar.

In [55]:
pipeline_xgb = Pipeline(steps=[
    ("preprocesamiento", MinMaxScaler(feature_range=(0, 1))),
    ("modelo", XGBClassifier(
        objective="binary:logistic",
        eval_metric="logloss",
        tree_method="hist",
        random_state=0,
        n_jobs=1
    ))
])

### Rejilla de hiperparámetros.

In [56]:
#rejilla_xgb = {
#    "modelo__n_estimators": [100, 200, 300],
#    "modelo__max_depth": [3, 5, 7],
#    "modelo__learning_rate": [0.01, 0.1, 0.2],
#    "modelo__subsample": [0.8, 1.0],
#    "modelo__colsample_bytree": [0.8, 1.0]
#}
rejilla_xgb = {
    "modelo__n_estimators": [300],
    "modelo__max_depth": [5],
    "modelo__learning_rate": [0.1],
    "modelo__subsample": [1.0],
    "modelo__colsample_bytree": [1.0]
}

### GridSearch -aleatorio-

In [58]:
grid_search_xgb = GridSearchCV(
    estimator=pipeline_xgb,
    param_grid=rejilla_xgb,
    scoring="f1",
    cv=5,
    n_jobs=-1,
    verbose=1,
    return_train_score=True
)

### GridSearch -espacial-

In [59]:
grid_xgb_esp = GridSearchCV(
    estimator=pipeline_xgb,
    param_grid=rejilla_xgb,
    scoring="f1",
    cv=cv_espacial,
    n_jobs=-1,
    return_train_score=True
)

### Entrenamiento del modelo.

In [60]:
grid_search_xgb.fit(X_train_aleatorio, y_train_aleatorio)

Fitting 5 folds for each of 1 candidates, totalling 5 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocesamiento', MinMaxScaler()),
                                       ('modelo',
                                        XGBClassifier(base_score=None,
                                                      booster=None,
                                                      callbacks=None,
                                                      colsample_bylevel=None,
                                                      colsample_bynode=None,
                                                      colsample_bytree=None,
                                                      device=None,
                                                      early_stopping_rounds=None,
                                                      enable_categorical=True,
                                                      eval_metric='logloss',
                                                      feature_types=None,
                                                      feature_weights=None,
                                                      gamma=None...
                                                      min_child_weight=None,
                                                      missing=nan,
                                                      monotone_constraints=None,
                                                      multi_strategy=None,
                                                      n_estimators=None,
                                                      n_jobs=1,
                                                      num_parallel_tree=None, ...))]),
             n_jobs=-1,
             param_grid={'modelo__colsample_bytree': [1.0],
                         'modelo__learning_rate': [0.1],
                         'modelo__max_depth': [5],
                         'modelo__n_estimators': [300],
                         'modelo__subsample': [1.0]},
             return_train_score=True, scoring='f1', verbose=1)

In [61]:
grid_xgb_esp.fit(X_train_esp,y_train_esp,groups=groups_train_esp) #espacial

GridSearchCV(cv=StratifiedGroupKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('preprocesamiento', MinMaxScaler()),
                                       ('modelo',
                                        XGBClassifier(base_score=None,
                                                      booster=None,
                                                      callbacks=None,
                                                      colsample_bylevel=None,
                                                      colsample_bynode=None,
                                                      colsample_bytree=None,
                                                      device=None,
                                                      early_stopping_rounds=None,
                                                      enable_categorical=True,
                                                      eval_metric=...
                                                      max_leaves=None,
                                                      min_child_weight=None,
                                                      missing=nan,
                                                      monotone_constraints=None,
                                                      multi_strategy=None,
                                                      n_estimators=None,
                                                      n_jobs=1,
                                                      num_parallel_tree=None, ...))]),
             n_jobs=-1,
             param_grid={'modelo__colsample_bytree': [1.0],
                         'modelo__learning_rate': [0.1],
                         'modelo__max_depth': [5],
                         'modelo__n_estimators': [300],
                         'modelo__subsample': [1.0]},
             return_train_score=True, scoring='f1')

### Mejor modelo e hiperparámetros.

In [62]:
mejor_xgb = grid_search_xgb.best_estimator_
print("Mejor accuracy en validación:", grid_search_xgb.best_score_)
print("Mejores hiperparámetros:", grid_search_xgb.best_params_)

Mejor accuracy en validación: 0.821010101010101
Mejores hiperparámetros: {'modelo__colsample_bytree': 1.0, 'modelo__learning_rate': 0.1, 'modelo__max_depth': 5, 'modelo__n_estimators': 300, 'modelo__subsample': 1.0}

### Evaluación de modelos espaciales

In [63]:
mejor_rl_esp = grid_rl_esp.best_estimator_
mejor_rf_esp = grid_rf_esp.best_estimator_
mejor_xgb_esp = grid_xgb_esp.best_estimator_

### Predicciones modelos espaciales

In [64]:
pred_rl_esp = mejor_rl_esp.predict(X_test_esp)

pred_rf_esp = mejor_rf_esp.predict(X_test_esp)

pred_xgb_esp = mejor_xgb_esp.predict(X_test_esp)

### Probabilidades de modelos espaciales

In [65]:
prob_rl_esp = mejor_rl_esp.predict_proba(X_test_esp)[:, 1]

prob_rf_esp = mejor_rf_esp.predict_proba(X_test_esp)[:, 1]

prob_xgb_esp = mejor_xgb_esp.predict_proba(X_test_esp)[:, 1]

### Con respecto a las versiones originales (aleatorias)

In [67]:
#MEJOR MODELO
mejor_rl_aleatorio = grid_search_rl.best_estimator_
mejor_rf_aleatorio = grid_search_rf.best_estimator_
mejor_xgb_aleatorio = grid_search_xgb.best_estimator_

#PROBABILIDADES
pred_rl_aleatorio = mejor_rl_aleatorio.predict(X_test_aleatorio)
prob_rl_aleatorio = mejor_rl_aleatorio.predict_proba(X_test_aleatorio)[:, 1]

pred_rf_aleatorio = mejor_rf_aleatorio.predict(X_test_aleatorio)
prob_rf_aleatorio = mejor_rf_aleatorio.predict_proba(X_test_aleatorio)[:, 1]

pred_xgb_aleatorio = mejor_xgb_aleatorio.predict(X_test_aleatorio)
prob_xgb_aleatorio = mejor_xgb_aleatorio.predict_proba(X_test_aleatorio)[:, 1]

## Resultados

### Métricas

In [69]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    balanced_accuracy_score,
    roc_auc_score
)


def evaluar_modelo(y_true, y_pred, y_prob):

    return {
        "Accuracy":
            accuracy_score(
                y_true,
                y_pred
            ),

        "Balanced Accuracy":
            balanced_accuracy_score(
                y_true,
                y_pred
            ),

        "Precision":
            precision_score(
                y_true,
                y_pred,
                zero_division=0
            ),

        "Recall":
            recall_score(
                y_true,
                y_pred,
                zero_division=0
            ),

        "F1":
            f1_score(
                y_true,
                y_pred,
                zero_division=0
            ),

        "ROC-AUC":
            roc_auc_score(
                y_true,
                y_prob
            )
    }

### Espaciales

In [70]:
resultados_esp = {
    "Regresión Logística":
        evaluar_modelo(
            y_test_esp,
            pred_rl_esp,
            prob_rl_esp
        ),

    "Random Forest":
        evaluar_modelo(
            y_test_esp,
            pred_rf_esp,
            prob_rf_esp
        ),

    "XGBoost":
        evaluar_modelo(
            y_test_esp,
            pred_xgb_esp,
            prob_xgb_esp
        )
}

df_esp = (
    pd.DataFrame(resultados_esp)
    .T
)

display(df_esp)

,Accuracy,Balanced Accuracy,Precision,Recall,F1,ROC-AUC
Regresión Logística,0.809524,0.813636,0.750000,0.9,0.818182,0.909091
Random Forest,0.857143,0.863636,0.769231,1.0,0.869565,0.909091
XGBoost,0.857143,0.863636,0.769231,1.0,0.869565,0.900000

### Aleatorios

In [72]:
resultados_aleatorios = {
    "Regresión Logística":
        evaluar_modelo(
            y_test_aleatorio,
            pred_rl_aleatorio,
            prob_rl_aleatorio
        ),

    "Random Forest":
        evaluar_modelo(
            y_test_aleatorio,
            pred_rf_aleatorio,
            prob_rf_aleatorio
        ),

    "XGBoost":
        evaluar_modelo(
            y_test_aleatorio,
            pred_xgb_aleatorio,
            prob_xgb_aleatorio
        )
}

df_aleatorio = (
    pd.DataFrame(resultados_aleatorios)
    .T
)

display(df_aleatorio)

,Accuracy,Balanced Accuracy,Precision,Recall,F1,ROC-AUC
Regresión Logística,0.909091,0.916667,0.833333,1.0,0.909091,0.950000
Random Forest,0.909091,0.916667,0.833333,1.0,0.909091,0.983333
XGBoost,0.954545,0.958333,0.909091,1.0,0.952381,0.950000

### Comparación entre la versión original (aleatoria) y la espacial

In [73]:
comparacion = pd.concat(
    {
        "Aleatoria": df_aleatorio,
        "Espacial": df_esp
    },
    names=[
        "Validación",
        "Modelo"
    ]
)

display(
    comparacion.round(3)
)

                                Accuracy  Balanced Accuracy  Precision  \
Validación Modelo
Aleatoria  Regresión Logística     0.909              0.917      0.833
           Random Forest           0.909              0.917      0.833
           XGBoost                 0.955              0.958      0.909
Espacial   Regresión Logística     0.810              0.814      0.750
           Random Forest           0.857              0.864      0.769
           XGBoost                 0.857              0.864      0.769

                                Recall     F1  ROC-AUC
Validación Modelo
Aleatoria  Regresión Logística     1.0  0.909    0.950
           Random Forest           1.0  0.909    0.983
           XGBoost                 1.0  0.952    0.950
Espacial   Regresión Logística     0.9  0.818    0.909
           Random Forest           1.0  0.870    0.909
           XGBoost                 1.0  0.870    0.900

### Diferencia de las métricas

In [74]:
diferencias = (df_esp -df_aleatorio)
display(diferencias.round(3))

,Accuracy,Balanced Accuracy,Precision,Recall,F1,ROC-AUC
Regresión Logística,-0.100,-0.103,-0.083,-0.1,-0.091,-0.041
Random Forest,-0.052,-0.053,-0.064,0.0,-0.040,-0.074
XGBoost,-0.097,-0.095,-0.140,0.0,-0.083,-0.050